### ISSUE TITLE
Mirror string in Czech is too long for the caption on it in MTC

### ISSUE THREAD

**Issue by rampa3** [Neos-Metaverse/NeosLocale#394]
![image](https://user-images.githubusercontent.com/68955305/116049781-37531980-a666-11eb-949a-bd8b5d45601f.png)

"O" in word "Zrcadlo" is going to second line...

**Comment by Frooxius** [comment]
Passed to the builder team, thanks!

**Comment by RueShejn** [comment]
This has been fixed!

**Comment by rampa3** [comment]
Issue resolved.
