### ISSUE TITLE
Request: Point Clouds with an option to fix the point size, instead that the point size get smaller when the user get closer.

### ISSUE THREAD

**Issue by MartnDe** [Neos-Metaverse/NeosLocale#443]
Hello Neos Team.

I am experimenting in Neos with real volumetric video recordings. At the moment I use 2 Azure Kinect locally matched and recorded(Frontand Back) (soon 4 sensors from all sides). I export then PLY Streams, this stream I import to Neos as they are PLY Point Cloud they have the typical behaving of an Point Cloud. I mean that the point size gets smaller when the user get closer. I would love to have the chance to set the point size to a fixed size not only to keep the solid look of an point cloud as well to reduce the points and rise the point size accordingly to the imported file that I can maybe even reduce the amount of points. I experimented with 300 frames and of an 30fps recording each frame is around 10mb, this is already a 60% compression of the original size and I could compress to 85 or 90% (5mb or 3,5mb) if I would be able to fix or adjust the point size ... the super extreme version would be that each point could be handled as particle cast ... this would allow to create very advance looks of moving volumetric Point Cloud recordings, but for the moment I would first of all request a adjustable point size to an float or an int ... I hope this will be possible ... 

Thx and greatings 
Martn D. 
https://www.martnd.com
https://vimeo.com/martnd
https://sketchfab.com/MartnDe

Somehow by this message it is now public ... that Neos is one of the first Social VR platforms which can handle real Volumetric Video. (you can walk around the recording and see the recorded character really from all side so not "fake volumetric".

I would be more then happy to show my volumetric recording result inside of neos to the neos team, I plan as celebration of volumetric video inside of NEOS a open house concert with recorded artists inside of my private "digital twin" flat which I imported in NEOS.

**Comment by H3BO3** [comment]
Hello, this is the Locale repository. Please submit this issue to the NeosPublic repository. https://github.com/Neos-Metaverse/NeosPublic/issues

**Comment by H3BO3** [comment]
Do you mind closing this issue @MartnDe ?
