### ISSUE TITLE
Duplicated strings in the new MTC streaming room part of the locale file

### ISSUE THREAD

**Issue by rampa3** [Neos-Metaverse/NeosLocale#444]
![image](https://user-images.githubusercontent.com/68955305/121326674-12172380-c913-11eb-9dc9-5d3d42a48857.png)
There are duplicated strings present in the source language file... (The ones in the screenshot are just an example. There are more of the duplicates.)

**Comment by Frooxius** [comment]
Ah good catch thank you! Should be fixed here: https://github.com/Neos-Metaverse/NeosLocale/commit/99927d67dca61fa908f603d44d7c86e09070657f

I'll have to wait on a word from @RueShejn to see if those are fully correct, but I think they should be.
