### ISSUE TITLE
Idea/suggestion: Make way to archive and reload already translated MMC strings

### ISSUE THREAD

**Issue by rampa3** [Neos-Metaverse/NeosLocale#562]
Just a little idea:
Would it be possible to make a script or other way to pull out/place back the MMC strings on Neos's side, if they didn't changed too much and aren't in use at given moment? I feel that outright deleting them after MMC and having them redone yearly is wasting of translation, if even partially you could use the ones from last year.

I would like to see opinions on this from as much people as possible. I thank everyone who will read this, think about it and post their opinion in comment for their time they spent thinking about this idea.

**Comment by 3x1t-5tyl3** [comment]
I actually agree here. Throwing them out every time seems like it'd waste quite a bit of time for users who do translations.

Even if only partial usage; at-least then you could re-use lines and it would save a lot of time in the long run.
Archiving them seems like a smart thing to do.

**Comment by Frooxius** [comment]
There's no need for this, the Git source control (and GitHub as a result) is essentially a complete history of changes that's fully searchable. Every single change is archived.

You can simply search for the appropriate commits or pieces of code like this: https://github.com/Neos-Metaverse/NeosLocale/search?q=MMC&type=commits

**Comment by ProbablePrime** [comment]
I meant to resurrect strings for everyone that submitted them yesterday but got caught up in other matters. 

I'll be doing this for any missing but previously submitted strings today. 

For git its a common practice to use it as storage for older code instead of commenting it out you can read more here: https://kentcdodds.com/blog/please-dont-commit-commented-out-code

**Comment by ProbablePrime** [comment]
Actually on second thought looking at some of them, it is better if the one doing the translations resurrects them. 

I wouldn't want the strings to be incomplete, they can use the old commits as a baseline to work from.

**Comment by rampa3** [comment]
> 
> 
> Actually on second thought looking at some of them, it is better if the one doing the translations resurrects them.
> 
> I wouldn't want the strings to be incomplete, they can use the old commits as a baseline to work from.

I agree. I think more discussion is not needed.
